jobs:
  - name: pipelines-demo-manifest
    type: manifest
    steps:
     - IN: pipelines-demo-image
     - IN: pipelines-demo-image2
     - IN: pipelines-demo-image3
     - IN: pipelines-demo-image4
     - IN: pipelines-demo-image5
     - TASK: managed

  - name: deploy-pipelines-demo
    type: deploy
    flags:
      - job-flag
    steps:
      - IN: pipelines-demo-manifest
      - IN: docker-options
      - IN: ecs-cluster
      - IN: replicas
      - TASK: managed
        deployMethod: upgrade

  - name: runSh
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - TASK:
        - script: echo 'This block executes when the TASK starts'

  - name: runSh2
    type: runSh
    steps:
      - IN: pipelines-demo-manifest
      - TASK:
        - script: echo 'This block executes when the TASK starts'


  - name: runSh3
    type: runSh
    steps:
      - IN: deploy-pipelines-demo
      - TASK:
        - script: echo 'This block executes when the TASK starts'


  - name: runSh4
    type: runSh
    steps:
      - IN: runSh3
      - TASK:
        - script: echo 'This block executes when the TASK starts'


  - name: runSh5
    type: runSh
    steps:
      - IN: runSh4
      - TASK:
        - script: echo 'This block executes when the TASK starts'

  - name: runSh6
    type: runSh
    steps:
      - IN: runSh5
      - TASK:
        - script: echo 'This block executes when the TASK starts'
    flags:
      - dv
      
  - name: runSh7
    type: runSh
    steps:
      - IN: runSh6
      - TASK:
        - script: echo 'This block executes when the TASK starts'
    flags:
      - dv
  - name: runSh8-runSh8-runSh8-runSh8-runSh8-runSh8
    type: runCi
    steps:
      - IN: runSh7
      - TASK:
        - script: echo 'This block executes when the TASK starts'
    flags:
      - dv


